/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPaginatedWorkoutEventsFromDiscriminatorValue, type PaginatedWorkoutEvents } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/workouts/events
 */
export interface EventsRequestBuilder extends BaseRequestBuilder<EventsRequestBuilder> {
    /**
     * Returns a paginated array of workout events, indicating updates or deletions.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PaginatedWorkoutEvents>}
     */
     get(requestConfiguration?: RequestConfiguration<EventsRequestBuilderGetQueryParameters> | undefined) : Promise<PaginatedWorkoutEvents | undefined>;
    /**
     * Returns a paginated array of workout events, indicating updates or deletions.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<EventsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns a paginated array of workout events, indicating updates or deletions.
 */
export interface EventsRequestBuilderGetQueryParameters {
    /**
     * Page number (Must be 1 or greater)
     */
    page?: number;
    /**
     * Number of items on the requested page (Max 10)
     */
    pageSize?: number;
    since?: string;
}
/**
 * Uri template for the request builder.
 */
export const EventsRequestBuilderUriTemplate = "{+baseurl}/v1/workouts/events{?page*,pageSize*,since*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const EventsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: EventsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createPaginatedWorkoutEventsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
