# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm ci --ignore-scripts

# Copy the rest of the application
COPY . ./

ENV NODE_ENV=production
ENV HEVY_API_KEY=your-api-key-here

# Build the application
RUN npm run build

CMD [ "npm", "start" ]
