/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeletedWorkout}
 */
// @ts-ignore
export function createDeletedWorkoutFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDeletedWorkout;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ExerciseTemplate}
 */
// @ts-ignore
export function createExerciseTemplateFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoExerciseTemplate;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DeletedWorkout | UpdatedWorkout}
 */
// @ts-ignore
export function createPaginatedWorkoutEvents_eventsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaginatedWorkoutEvents_events;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PaginatedWorkoutEvents}
 */
// @ts-ignore
export function createPaginatedWorkoutEventsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPaginatedWorkoutEvents;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostRoutineFolderRequestBody_routine_folder}
 */
// @ts-ignore
export function createPostRoutineFolderRequestBody_routine_folderFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostRoutineFolderRequestBody_routine_folder;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostRoutineFolderRequestBody}
 */
// @ts-ignore
export function createPostRoutineFolderRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostRoutineFolderRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostRoutinesRequestBody_routine}
 */
// @ts-ignore
export function createPostRoutinesRequestBody_routineFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostRoutinesRequestBody_routine;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostRoutinesRequestBody}
 */
// @ts-ignore
export function createPostRoutinesRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostRoutinesRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostRoutinesRequestExercise}
 */
// @ts-ignore
export function createPostRoutinesRequestExerciseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostRoutinesRequestExercise;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostRoutinesRequestSet}
 */
// @ts-ignore
export function createPostRoutinesRequestSetFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostRoutinesRequestSet;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostWorkoutsRequestBody_workout}
 */
// @ts-ignore
export function createPostWorkoutsRequestBody_workoutFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostWorkoutsRequestBody_workout;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostWorkoutsRequestBody}
 */
// @ts-ignore
export function createPostWorkoutsRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostWorkoutsRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostWorkoutsRequestExercise}
 */
// @ts-ignore
export function createPostWorkoutsRequestExerciseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostWorkoutsRequestExercise;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PostWorkoutsRequestSet}
 */
// @ts-ignore
export function createPostWorkoutsRequestSetFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPostWorkoutsRequestSet;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PutRoutinesRequestBody_routine}
 */
// @ts-ignore
export function createPutRoutinesRequestBody_routineFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPutRoutinesRequestBody_routine;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PutRoutinesRequestBody}
 */
// @ts-ignore
export function createPutRoutinesRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPutRoutinesRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PutRoutinesRequestExercise}
 */
// @ts-ignore
export function createPutRoutinesRequestExerciseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPutRoutinesRequestExercise;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PutRoutinesRequestSet}
 */
// @ts-ignore
export function createPutRoutinesRequestSetFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPutRoutinesRequestSet;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Routine_exercises_sets}
 */
// @ts-ignore
export function createRoutine_exercises_setsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRoutine_exercises_sets;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Routine_exercises}
 */
// @ts-ignore
export function createRoutine_exercisesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRoutine_exercises;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RoutineFolder}
 */
// @ts-ignore
export function createRoutineFolderFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRoutineFolder;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Routine}
 */
// @ts-ignore
export function createRoutineFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRoutine;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdatedWorkout}
 */
// @ts-ignore
export function createUpdatedWorkoutFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdatedWorkout;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Workout_exercises_sets}
 */
// @ts-ignore
export function createWorkout_exercises_setsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWorkout_exercises_sets;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Workout_exercises}
 */
// @ts-ignore
export function createWorkout_exercisesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWorkout_exercises;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Workout}
 */
// @ts-ignore
export function createWorkoutFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWorkout;
}
export interface DeletedWorkout extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * A date string indicating when the workout was deleted
     */
    deletedAt?: string | null;
    /**
     * The unique identifier of the deleted workout
     */
    id?: string | null;
    /**
     * Indicates the type of the event (deleted)
     */
    type?: string | null;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDeletedWorkout(deletedWorkout: Partial<DeletedWorkout> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "deleted_at": n => { deletedWorkout.deletedAt = n.getStringValue(); },
        "id": n => { deletedWorkout.id = n.getStringValue(); },
        "type": n => { deletedWorkout.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoExerciseTemplate(exerciseTemplate: Partial<ExerciseTemplate> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { exerciseTemplate.id = n.getStringValue(); },
        "is_custom": n => { exerciseTemplate.isCustom = n.getBooleanValue(); },
        "primary_muscle_group": n => { exerciseTemplate.primaryMuscleGroup = n.getStringValue(); },
        "secondary_muscle_groups": n => { exerciseTemplate.secondaryMuscleGroups = n.getCollectionOfPrimitiveValues<string>(); },
        "title": n => { exerciseTemplate.title = n.getStringValue(); },
        "type": n => { exerciseTemplate.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaginatedWorkoutEvents(paginatedWorkoutEvents: Partial<PaginatedWorkoutEvents> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "events": n => { paginatedWorkoutEvents.events = n.getCollectionOfObjectValues<DeletedWorkout>(createDeletedWorkoutFromDiscriminatorValue) ?? n.getCollectionOfObjectValues<UpdatedWorkout>(createUpdatedWorkoutFromDiscriminatorValue); },
        "page": n => { paginatedWorkoutEvents.page = n.getNumberValue(); },
        "page_count": n => { paginatedWorkoutEvents.pageCount = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPaginatedWorkoutEvents_events(paginatedWorkoutEvents_events: Partial<DeletedWorkout | UpdatedWorkout> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoDeletedWorkout(paginatedWorkoutEvents_events as DeletedWorkout),
        ...deserializeIntoUpdatedWorkout(paginatedWorkoutEvents_events as UpdatedWorkout),
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostRoutineFolderRequestBody(postRoutineFolderRequestBody: Partial<PostRoutineFolderRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "routine_folder": n => { postRoutineFolderRequestBody.routineFolder = n.getObjectValue<PostRoutineFolderRequestBody_routine_folder>(createPostRoutineFolderRequestBody_routine_folderFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostRoutineFolderRequestBody_routine_folder(postRoutineFolderRequestBody_routine_folder: Partial<PostRoutineFolderRequestBody_routine_folder> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "title": n => { postRoutineFolderRequestBody_routine_folder.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostRoutinesRequestBody(postRoutinesRequestBody: Partial<PostRoutinesRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "routine": n => { postRoutinesRequestBody.routine = n.getObjectValue<PostRoutinesRequestBody_routine>(createPostRoutinesRequestBody_routineFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostRoutinesRequestBody_routine(postRoutinesRequestBody_routine: Partial<PostRoutinesRequestBody_routine> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "exercises": n => { postRoutinesRequestBody_routine.exercises = n.getCollectionOfObjectValues<PostRoutinesRequestExercise>(createPostRoutinesRequestExerciseFromDiscriminatorValue); },
        "folder_id": n => { postRoutinesRequestBody_routine.folderId = n.getNumberValue(); },
        "notes": n => { postRoutinesRequestBody_routine.notes = n.getStringValue(); },
        "title": n => { postRoutinesRequestBody_routine.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostRoutinesRequestExercise(postRoutinesRequestExercise: Partial<PostRoutinesRequestExercise> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "exercise_template_id": n => { postRoutinesRequestExercise.exerciseTemplateId = n.getStringValue(); },
        "notes": n => { postRoutinesRequestExercise.notes = n.getStringValue(); },
        "rest_seconds": n => { postRoutinesRequestExercise.restSeconds = n.getNumberValue(); },
        "sets": n => { postRoutinesRequestExercise.sets = n.getCollectionOfObjectValues<PostRoutinesRequestSet>(createPostRoutinesRequestSetFromDiscriminatorValue); },
        "superset_id": n => { postRoutinesRequestExercise.supersetId = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostRoutinesRequestSet(postRoutinesRequestSet: Partial<PostRoutinesRequestSet> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "custom_metric": n => { postRoutinesRequestSet.customMetric = n.getNumberValue(); },
        "distance_meters": n => { postRoutinesRequestSet.distanceMeters = n.getNumberValue(); },
        "duration_seconds": n => { postRoutinesRequestSet.durationSeconds = n.getNumberValue(); },
        "reps": n => { postRoutinesRequestSet.reps = n.getNumberValue(); },
        "type": n => { postRoutinesRequestSet.type = n.getEnumValue<PostRoutinesRequestSet_type>(PostRoutinesRequestSet_typeObject); },
        "weight_kg": n => { postRoutinesRequestSet.weightKg = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostWorkoutsRequestBody(postWorkoutsRequestBody: Partial<PostWorkoutsRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "workout": n => { postWorkoutsRequestBody.workout = n.getObjectValue<PostWorkoutsRequestBody_workout>(createPostWorkoutsRequestBody_workoutFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostWorkoutsRequestBody_workout(postWorkoutsRequestBody_workout: Partial<PostWorkoutsRequestBody_workout> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { postWorkoutsRequestBody_workout.description = n.getStringValue(); },
        "end_time": n => { postWorkoutsRequestBody_workout.endTime = n.getStringValue(); },
        "exercises": n => { postWorkoutsRequestBody_workout.exercises = n.getCollectionOfObjectValues<PostWorkoutsRequestExercise>(createPostWorkoutsRequestExerciseFromDiscriminatorValue); },
        "is_private": n => { postWorkoutsRequestBody_workout.isPrivate = n.getBooleanValue(); },
        "start_time": n => { postWorkoutsRequestBody_workout.startTime = n.getStringValue(); },
        "title": n => { postWorkoutsRequestBody_workout.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostWorkoutsRequestExercise(postWorkoutsRequestExercise: Partial<PostWorkoutsRequestExercise> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "exercise_template_id": n => { postWorkoutsRequestExercise.exerciseTemplateId = n.getStringValue(); },
        "notes": n => { postWorkoutsRequestExercise.notes = n.getStringValue(); },
        "sets": n => { postWorkoutsRequestExercise.sets = n.getCollectionOfObjectValues<PostWorkoutsRequestSet>(createPostWorkoutsRequestSetFromDiscriminatorValue); },
        "superset_id": n => { postWorkoutsRequestExercise.supersetId = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPostWorkoutsRequestSet(postWorkoutsRequestSet: Partial<PostWorkoutsRequestSet> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "custom_metric": n => { postWorkoutsRequestSet.customMetric = n.getNumberValue(); },
        "distance_meters": n => { postWorkoutsRequestSet.distanceMeters = n.getNumberValue(); },
        "duration_seconds": n => { postWorkoutsRequestSet.durationSeconds = n.getNumberValue(); },
        "reps": n => { postWorkoutsRequestSet.reps = n.getNumberValue(); },
        "rpe": n => { postWorkoutsRequestSet.rpe = n.getNumberValue(); },
        "type": n => { postWorkoutsRequestSet.type = n.getEnumValue<PostWorkoutsRequestSet_type>(PostWorkoutsRequestSet_typeObject); },
        "weight_kg": n => { postWorkoutsRequestSet.weightKg = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPutRoutinesRequestBody(putRoutinesRequestBody: Partial<PutRoutinesRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "routine": n => { putRoutinesRequestBody.routine = n.getObjectValue<PutRoutinesRequestBody_routine>(createPutRoutinesRequestBody_routineFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPutRoutinesRequestBody_routine(putRoutinesRequestBody_routine: Partial<PutRoutinesRequestBody_routine> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "exercises": n => { putRoutinesRequestBody_routine.exercises = n.getCollectionOfObjectValues<PutRoutinesRequestExercise>(createPutRoutinesRequestExerciseFromDiscriminatorValue); },
        "notes": n => { putRoutinesRequestBody_routine.notes = n.getStringValue(); },
        "title": n => { putRoutinesRequestBody_routine.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPutRoutinesRequestExercise(putRoutinesRequestExercise: Partial<PutRoutinesRequestExercise> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "exercise_template_id": n => { putRoutinesRequestExercise.exerciseTemplateId = n.getStringValue(); },
        "notes": n => { putRoutinesRequestExercise.notes = n.getStringValue(); },
        "rest_seconds": n => { putRoutinesRequestExercise.restSeconds = n.getNumberValue(); },
        "sets": n => { putRoutinesRequestExercise.sets = n.getCollectionOfObjectValues<PutRoutinesRequestSet>(createPutRoutinesRequestSetFromDiscriminatorValue); },
        "superset_id": n => { putRoutinesRequestExercise.supersetId = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPutRoutinesRequestSet(putRoutinesRequestSet: Partial<PutRoutinesRequestSet> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "custom_metric": n => { putRoutinesRequestSet.customMetric = n.getNumberValue(); },
        "distance_meters": n => { putRoutinesRequestSet.distanceMeters = n.getNumberValue(); },
        "duration_seconds": n => { putRoutinesRequestSet.durationSeconds = n.getNumberValue(); },
        "reps": n => { putRoutinesRequestSet.reps = n.getNumberValue(); },
        "type": n => { putRoutinesRequestSet.type = n.getEnumValue<PutRoutinesRequestSet_type>(PutRoutinesRequestSet_typeObject); },
        "weight_kg": n => { putRoutinesRequestSet.weightKg = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRoutine(routine: Partial<Routine> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "created_at": n => { routine.createdAt = n.getStringValue(); },
        "exercises": n => { routine.exercises = n.getCollectionOfObjectValues<Routine_exercises>(createRoutine_exercisesFromDiscriminatorValue); },
        "folder_id": n => { routine.folderId = n.getNumberValue(); },
        "id": n => { routine.id = n.getStringValue(); },
        "title": n => { routine.title = n.getStringValue(); },
        "updated_at": n => { routine.updatedAt = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRoutine_exercises(routine_exercises: Partial<Routine_exercises> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "exercise_template_id": n => { routine_exercises.exerciseTemplateId = n.getStringValue(); },
        "index": n => { routine_exercises.index = n.getNumberValue(); },
        "notes": n => { routine_exercises.notes = n.getStringValue(); },
        "sets": n => { routine_exercises.sets = n.getCollectionOfObjectValues<Routine_exercises_sets>(createRoutine_exercises_setsFromDiscriminatorValue); },
        "supersets_id": n => { routine_exercises.supersetsId = n.getNumberValue(); },
        "title": n => { routine_exercises.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRoutine_exercises_sets(routine_exercises_sets: Partial<Routine_exercises_sets> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "custom_metric": n => { routine_exercises_sets.customMetric = n.getNumberValue(); },
        "distance_meters": n => { routine_exercises_sets.distanceMeters = n.getNumberValue(); },
        "duration_seconds": n => { routine_exercises_sets.durationSeconds = n.getNumberValue(); },
        "index": n => { routine_exercises_sets.index = n.getNumberValue(); },
        "reps": n => { routine_exercises_sets.reps = n.getNumberValue(); },
        "rpe": n => { routine_exercises_sets.rpe = n.getNumberValue(); },
        "type": n => { routine_exercises_sets.type = n.getStringValue(); },
        "weight_kg": n => { routine_exercises_sets.weightKg = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRoutineFolder(routineFolder: Partial<RoutineFolder> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "created_at": n => { routineFolder.createdAt = n.getStringValue(); },
        "id": n => { routineFolder.id = n.getNumberValue(); },
        "index": n => { routineFolder.index = n.getNumberValue(); },
        "title": n => { routineFolder.title = n.getStringValue(); },
        "updated_at": n => { routineFolder.updatedAt = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdatedWorkout(updatedWorkout: Partial<UpdatedWorkout> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "type": n => { updatedWorkout.type = n.getStringValue(); },
        "workout": n => { updatedWorkout.workout = n.getObjectValue<Workout>(createWorkoutFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWorkout(workout: Partial<Workout> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "created_at": n => { workout.createdAt = n.getStringValue(); },
        "description": n => { workout.description = n.getStringValue(); },
        "end_time": n => { workout.endTime = n.getNumberValue(); },
        "exercises": n => { workout.exercises = n.getCollectionOfObjectValues<Workout_exercises>(createWorkout_exercisesFromDiscriminatorValue); },
        "id": n => { workout.id = n.getStringValue(); },
        "start_time": n => { workout.startTime = n.getNumberValue(); },
        "title": n => { workout.title = n.getStringValue(); },
        "updated_at": n => { workout.updatedAt = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWorkout_exercises(workout_exercises: Partial<Workout_exercises> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "exercise_template_id": n => { workout_exercises.exerciseTemplateId = n.getStringValue(); },
        "index": n => { workout_exercises.index = n.getNumberValue(); },
        "notes": n => { workout_exercises.notes = n.getStringValue(); },
        "sets": n => { workout_exercises.sets = n.getCollectionOfObjectValues<Workout_exercises_sets>(createWorkout_exercises_setsFromDiscriminatorValue); },
        "supersets_id": n => { workout_exercises.supersetsId = n.getNumberValue(); },
        "title": n => { workout_exercises.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWorkout_exercises_sets(workout_exercises_sets: Partial<Workout_exercises_sets> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "custom_metric": n => { workout_exercises_sets.customMetric = n.getNumberValue(); },
        "distance_meters": n => { workout_exercises_sets.distanceMeters = n.getNumberValue(); },
        "duration_seconds": n => { workout_exercises_sets.durationSeconds = n.getNumberValue(); },
        "index": n => { workout_exercises_sets.index = n.getNumberValue(); },
        "reps": n => { workout_exercises_sets.reps = n.getNumberValue(); },
        "rpe": n => { workout_exercises_sets.rpe = n.getNumberValue(); },
        "type": n => { workout_exercises_sets.type = n.getStringValue(); },
        "weight_kg": n => { workout_exercises_sets.weightKg = n.getNumberValue(); },
    }
}
export interface ExerciseTemplate extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The exercise template ID.
     */
    id?: string | null;
    /**
     * A boolean indicating whether the exercise is a custom exercise.
     */
    isCustom?: boolean | null;
    /**
     * The primary muscle group of the exercise.
     */
    primaryMuscleGroup?: string | null;
    /**
     * The secondary muscle groups of the exercise.
     */
    secondaryMuscleGroups?: string[] | null;
    /**
     * The exercise title.
     */
    title?: string | null;
    /**
     * The exercise type.
     */
    type?: string | null;
}
export interface PaginatedWorkoutEvents extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * An array of workout events (either updated or deleted)
     */
    events?: (DeletedWorkout | UpdatedWorkout)[] | null;
    /**
     * The current page number
     */
    page?: number | null;
    /**
     * The total number of pages available
     */
    pageCount?: number | null;
}
export type PaginatedWorkoutEvents_events = DeletedWorkout | UpdatedWorkout;
export interface PostRoutineFolderRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The routine_folder property
     */
    routineFolder?: PostRoutineFolderRequestBody_routine_folder | null;
}
export interface PostRoutineFolderRequestBody_routine_folder extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The title of the routine folder.
     */
    title?: string | null;
}
export interface PostRoutinesRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The routine property
     */
    routine?: PostRoutinesRequestBody_routine | null;
}
export interface PostRoutinesRequestBody_routine extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The exercises property
     */
    exercises?: PostRoutinesRequestExercise[] | null;
    /**
     * The folder id the routine should be added to. Pass null to insert the routine into default "My Routines" folder
     */
    folderId?: number | null;
    /**
     * Additional notes for the routine.
     */
    notes?: string | null;
    /**
     * The title of the routine.
     */
    title?: string | null;
}
export interface PostRoutinesRequestExercise extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The ID of the exercise template.
     */
    exerciseTemplateId?: string | null;
    /**
     * Additional notes for the exercise.
     */
    notes?: string | null;
    /**
     * The rest time in seconds.
     */
    restSeconds?: number | null;
    /**
     * The sets property
     */
    sets?: PostRoutinesRequestSet[] | null;
    /**
     * The ID of the superset.
     */
    supersetId?: number | null;
}
export interface PostRoutinesRequestSet extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * A custom metric for the set. Currently used for steps and floors.
     */
    customMetric?: number | null;
    /**
     * The distance in meters.
     */
    distanceMeters?: number | null;
    /**
     * The duration in seconds.
     */
    durationSeconds?: number | null;
    /**
     * The number of repetitions.
     */
    reps?: number | null;
    /**
     * The type of the set.
     */
    type?: PostRoutinesRequestSet_type | null;
    /**
     * The weight in kilograms.
     */
    weightKg?: number | null;
}
export type PostRoutinesRequestSet_type = (typeof PostRoutinesRequestSet_typeObject)[keyof typeof PostRoutinesRequestSet_typeObject];
export interface PostWorkoutsRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The workout property
     */
    workout?: PostWorkoutsRequestBody_workout | null;
}
export interface PostWorkoutsRequestBody_workout extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * A description for the workout workout.
     */
    description?: string | null;
    /**
     * The time the workout ended.
     */
    endTime?: string | null;
    /**
     * The exercises property
     */
    exercises?: PostWorkoutsRequestExercise[] | null;
    /**
     * A boolean indicating if the workout is private.
     */
    isPrivate?: boolean | null;
    /**
     * The time the workout started.
     */
    startTime?: string | null;
    /**
     * The title of the workout.
     */
    title?: string | null;
}
export interface PostWorkoutsRequestExercise extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The ID of the exercise template.
     */
    exerciseTemplateId?: string | null;
    /**
     * Additional notes for the exercise.
     */
    notes?: string | null;
    /**
     * The sets property
     */
    sets?: PostWorkoutsRequestSet[] | null;
    /**
     * The ID of the superset.
     */
    supersetId?: number | null;
}
export interface PostWorkoutsRequestSet extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * A custom metric for the set. Currently used for steps and floors.
     */
    customMetric?: number | null;
    /**
     * The distance in meters.
     */
    distanceMeters?: number | null;
    /**
     * The duration in seconds.
     */
    durationSeconds?: number | null;
    /**
     * The number of repetitions.
     */
    reps?: number | null;
    /**
     * The Rating of Perceived Exertion (RPE).
     */
    rpe?: number | null;
    /**
     * The type of the set.
     */
    type?: PostWorkoutsRequestSet_type | null;
    /**
     * The weight in kilograms.
     */
    weightKg?: number | null;
}
export type PostWorkoutsRequestSet_type = (typeof PostWorkoutsRequestSet_typeObject)[keyof typeof PostWorkoutsRequestSet_typeObject];
export interface PutRoutinesRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The routine property
     */
    routine?: PutRoutinesRequestBody_routine | null;
}
export interface PutRoutinesRequestBody_routine extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The exercises property
     */
    exercises?: PutRoutinesRequestExercise[] | null;
    /**
     * Additional notes for the routine.
     */
    notes?: string | null;
    /**
     * The title of the routine.
     */
    title?: string | null;
}
export interface PutRoutinesRequestExercise extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The ID of the exercise template.
     */
    exerciseTemplateId?: string | null;
    /**
     * Additional notes for the exercise.
     */
    notes?: string | null;
    /**
     * The rest time in seconds.
     */
    restSeconds?: number | null;
    /**
     * The sets property
     */
    sets?: PutRoutinesRequestSet[] | null;
    /**
     * The ID of the superset.
     */
    supersetId?: number | null;
}
export interface PutRoutinesRequestSet extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * A custom metric for the set. Currently used for steps and floors.
     */
    customMetric?: number | null;
    /**
     * The distance in meters.
     */
    distanceMeters?: number | null;
    /**
     * The duration in seconds.
     */
    durationSeconds?: number | null;
    /**
     * The number of repetitions.
     */
    reps?: number | null;
    /**
     * The type of the set.
     */
    type?: PutRoutinesRequestSet_type | null;
    /**
     * The weight in kilograms.
     */
    weightKg?: number | null;
}
export type PutRoutinesRequestSet_type = (typeof PutRoutinesRequestSet_typeObject)[keyof typeof PutRoutinesRequestSet_typeObject];
export interface Routine extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * ISO 8601 timestamp of when the routine was created.
     */
    createdAt?: string | null;
    /**
     * The exercises property
     */
    exercises?: Routine_exercises[] | null;
    /**
     * The routine folder ID.
     */
    folderId?: number | null;
    /**
     * The routine ID.
     */
    id?: string | null;
    /**
     * The routine title.
     */
    title?: string | null;
    /**
     * ISO 8601 timestamp of when the routine was last updated.
     */
    updatedAt?: string | null;
}
export interface Routine_exercises extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The id of the exercise template. This can be used to fetch the exercise template.
     */
    exerciseTemplateId?: string | null;
    /**
     * Index indicating the order of the exercise in the routine.
     */
    index?: number | null;
    /**
     * Routine notes on the exercise
     */
    notes?: string | null;
    /**
     * The sets property
     */
    sets?: Routine_exercises_sets[] | null;
    /**
     * The id of the superset that the exercise belongs to. A value of null indicates the exercise is not part of a superset.
     */
    supersetsId?: number | null;
    /**
     * Title of the exercise
     */
    title?: string | null;
}
export interface Routine_exercises_sets extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * Custom metric logged for the set (Currently only used to log floors or steps for stair machine exercises)
     */
    customMetric?: number | null;
    /**
     * Number of meters logged for the set
     */
    distanceMeters?: number | null;
    /**
     * Number of seconds logged for the set
     */
    durationSeconds?: number | null;
    /**
     * Index indicating the order of the set in the routine.
     */
    index?: number | null;
    /**
     * Number of reps logged for the set
     */
    reps?: number | null;
    /**
     * RPE (Relative perceived exertion) value logged for the set
     */
    rpe?: number | null;
    /**
     * The type of set. This can be one of 'normal', 'warmup', 'dropset', 'failure'
     */
    type?: string | null;
    /**
     * Weight lifted in kilograms.
     */
    weightKg?: number | null;
}
export interface RoutineFolder extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * ISO 8601 timestamp of when the folder was created.
     */
    createdAt?: string | null;
    /**
     * The routine folder ID.
     */
    id?: number | null;
    /**
     * The routine folder index. Describes the order of the folder in the list.
     */
    index?: number | null;
    /**
     * The routine folder title.
     */
    title?: string | null;
    /**
     * ISO 8601 timestamp of when the folder was last updated.
     */
    updatedAt?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDeletedWorkout(writer: SerializationWriter, deletedWorkout: Partial<DeletedWorkout> | undefined | null = {}) : void {
    if (deletedWorkout) {
        writer.writeStringValue("deleted_at", deletedWorkout.deletedAt);
        writer.writeStringValue("id", deletedWorkout.id);
        writer.writeStringValue("type", deletedWorkout.type);
        writer.writeAdditionalData(deletedWorkout.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeExerciseTemplate(writer: SerializationWriter, exerciseTemplate: Partial<ExerciseTemplate> | undefined | null = {}) : void {
    if (exerciseTemplate) {
        writer.writeStringValue("id", exerciseTemplate.id);
        writer.writeBooleanValue("is_custom", exerciseTemplate.isCustom);
        writer.writeStringValue("primary_muscle_group", exerciseTemplate.primaryMuscleGroup);
        writer.writeCollectionOfPrimitiveValues<string>("secondary_muscle_groups", exerciseTemplate.secondaryMuscleGroups);
        writer.writeStringValue("title", exerciseTemplate.title);
        writer.writeStringValue("type", exerciseTemplate.type);
        writer.writeAdditionalData(exerciseTemplate.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaginatedWorkoutEvents(writer: SerializationWriter, paginatedWorkoutEvents: Partial<PaginatedWorkoutEvents> | undefined | null = {}) : void {
    if (paginatedWorkoutEvents) {
        writer.writeCollectionOfObjectValues<DeletedWorkout | UpdatedWorkout>("events", paginatedWorkoutEvents.events, serializePaginatedWorkoutEvents_events);
        writer.writeNumberValue("page", paginatedWorkoutEvents.page);
        writer.writeNumberValue("page_count", paginatedWorkoutEvents.pageCount);
        writer.writeAdditionalData(paginatedWorkoutEvents.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePaginatedWorkoutEvents_events(writer: SerializationWriter, paginatedWorkoutEvents_events: Partial<DeletedWorkout | UpdatedWorkout> | undefined | null = {}) : void {
    serializeDeletedWorkout(writer, paginatedWorkoutEvents_events as DeletedWorkout);
    serializeUpdatedWorkout(writer, paginatedWorkoutEvents_events as UpdatedWorkout);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostRoutineFolderRequestBody(writer: SerializationWriter, postRoutineFolderRequestBody: Partial<PostRoutineFolderRequestBody> | undefined | null = {}) : void {
    if (postRoutineFolderRequestBody) {
        writer.writeObjectValue<PostRoutineFolderRequestBody_routine_folder>("routine_folder", postRoutineFolderRequestBody.routineFolder, serializePostRoutineFolderRequestBody_routine_folder);
        writer.writeAdditionalData(postRoutineFolderRequestBody.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostRoutineFolderRequestBody_routine_folder(writer: SerializationWriter, postRoutineFolderRequestBody_routine_folder: Partial<PostRoutineFolderRequestBody_routine_folder> | undefined | null = {}) : void {
    if (postRoutineFolderRequestBody_routine_folder) {
        writer.writeStringValue("title", postRoutineFolderRequestBody_routine_folder.title);
        writer.writeAdditionalData(postRoutineFolderRequestBody_routine_folder.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostRoutinesRequestBody(writer: SerializationWriter, postRoutinesRequestBody: Partial<PostRoutinesRequestBody> | undefined | null = {}) : void {
    if (postRoutinesRequestBody) {
        writer.writeObjectValue<PostRoutinesRequestBody_routine>("routine", postRoutinesRequestBody.routine, serializePostRoutinesRequestBody_routine);
        writer.writeAdditionalData(postRoutinesRequestBody.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostRoutinesRequestBody_routine(writer: SerializationWriter, postRoutinesRequestBody_routine: Partial<PostRoutinesRequestBody_routine> | undefined | null = {}) : void {
    if (postRoutinesRequestBody_routine) {
        writer.writeCollectionOfObjectValues<PostRoutinesRequestExercise>("exercises", postRoutinesRequestBody_routine.exercises, serializePostRoutinesRequestExercise);
        writer.writeNumberValue("folder_id", postRoutinesRequestBody_routine.folderId);
        writer.writeStringValue("notes", postRoutinesRequestBody_routine.notes);
        writer.writeStringValue("title", postRoutinesRequestBody_routine.title);
        writer.writeAdditionalData(postRoutinesRequestBody_routine.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostRoutinesRequestExercise(writer: SerializationWriter, postRoutinesRequestExercise: Partial<PostRoutinesRequestExercise> | undefined | null = {}) : void {
    if (postRoutinesRequestExercise) {
        writer.writeStringValue("exercise_template_id", postRoutinesRequestExercise.exerciseTemplateId);
        writer.writeStringValue("notes", postRoutinesRequestExercise.notes);
        writer.writeNumberValue("rest_seconds", postRoutinesRequestExercise.restSeconds);
        writer.writeCollectionOfObjectValues<PostRoutinesRequestSet>("sets", postRoutinesRequestExercise.sets, serializePostRoutinesRequestSet);
        writer.writeNumberValue("superset_id", postRoutinesRequestExercise.supersetId);
        writer.writeAdditionalData(postRoutinesRequestExercise.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostRoutinesRequestSet(writer: SerializationWriter, postRoutinesRequestSet: Partial<PostRoutinesRequestSet> | undefined | null = {}) : void {
    if (postRoutinesRequestSet) {
        writer.writeNumberValue("custom_metric", postRoutinesRequestSet.customMetric);
        writer.writeNumberValue("distance_meters", postRoutinesRequestSet.distanceMeters);
        writer.writeNumberValue("duration_seconds", postRoutinesRequestSet.durationSeconds);
        writer.writeNumberValue("reps", postRoutinesRequestSet.reps);
        writer.writeEnumValue<PostRoutinesRequestSet_type>("type", postRoutinesRequestSet.type);
        writer.writeNumberValue("weight_kg", postRoutinesRequestSet.weightKg);
        writer.writeAdditionalData(postRoutinesRequestSet.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostWorkoutsRequestBody(writer: SerializationWriter, postWorkoutsRequestBody: Partial<PostWorkoutsRequestBody> | undefined | null = {}) : void {
    if (postWorkoutsRequestBody) {
        writer.writeObjectValue<PostWorkoutsRequestBody_workout>("workout", postWorkoutsRequestBody.workout, serializePostWorkoutsRequestBody_workout);
        writer.writeAdditionalData(postWorkoutsRequestBody.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostWorkoutsRequestBody_workout(writer: SerializationWriter, postWorkoutsRequestBody_workout: Partial<PostWorkoutsRequestBody_workout> | undefined | null = {}) : void {
    if (postWorkoutsRequestBody_workout) {
        writer.writeStringValue("description", postWorkoutsRequestBody_workout.description);
        writer.writeStringValue("end_time", postWorkoutsRequestBody_workout.endTime);
        writer.writeCollectionOfObjectValues<PostWorkoutsRequestExercise>("exercises", postWorkoutsRequestBody_workout.exercises, serializePostWorkoutsRequestExercise);
        writer.writeBooleanValue("is_private", postWorkoutsRequestBody_workout.isPrivate);
        writer.writeStringValue("start_time", postWorkoutsRequestBody_workout.startTime);
        writer.writeStringValue("title", postWorkoutsRequestBody_workout.title);
        writer.writeAdditionalData(postWorkoutsRequestBody_workout.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostWorkoutsRequestExercise(writer: SerializationWriter, postWorkoutsRequestExercise: Partial<PostWorkoutsRequestExercise> | undefined | null = {}) : void {
    if (postWorkoutsRequestExercise) {
        writer.writeStringValue("exercise_template_id", postWorkoutsRequestExercise.exerciseTemplateId);
        writer.writeStringValue("notes", postWorkoutsRequestExercise.notes);
        writer.writeCollectionOfObjectValues<PostWorkoutsRequestSet>("sets", postWorkoutsRequestExercise.sets, serializePostWorkoutsRequestSet);
        writer.writeNumberValue("superset_id", postWorkoutsRequestExercise.supersetId);
        writer.writeAdditionalData(postWorkoutsRequestExercise.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePostWorkoutsRequestSet(writer: SerializationWriter, postWorkoutsRequestSet: Partial<PostWorkoutsRequestSet> | undefined | null = {}) : void {
    if (postWorkoutsRequestSet) {
        writer.writeNumberValue("custom_metric", postWorkoutsRequestSet.customMetric);
        writer.writeNumberValue("distance_meters", postWorkoutsRequestSet.distanceMeters);
        writer.writeNumberValue("duration_seconds", postWorkoutsRequestSet.durationSeconds);
        writer.writeNumberValue("reps", postWorkoutsRequestSet.reps);
        writer.writeNumberValue("rpe", postWorkoutsRequestSet.rpe);
        writer.writeEnumValue<PostWorkoutsRequestSet_type>("type", postWorkoutsRequestSet.type);
        writer.writeNumberValue("weight_kg", postWorkoutsRequestSet.weightKg);
        writer.writeAdditionalData(postWorkoutsRequestSet.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePutRoutinesRequestBody(writer: SerializationWriter, putRoutinesRequestBody: Partial<PutRoutinesRequestBody> | undefined | null = {}) : void {
    if (putRoutinesRequestBody) {
        writer.writeObjectValue<PutRoutinesRequestBody_routine>("routine", putRoutinesRequestBody.routine, serializePutRoutinesRequestBody_routine);
        writer.writeAdditionalData(putRoutinesRequestBody.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePutRoutinesRequestBody_routine(writer: SerializationWriter, putRoutinesRequestBody_routine: Partial<PutRoutinesRequestBody_routine> | undefined | null = {}) : void {
    if (putRoutinesRequestBody_routine) {
        writer.writeCollectionOfObjectValues<PutRoutinesRequestExercise>("exercises", putRoutinesRequestBody_routine.exercises, serializePutRoutinesRequestExercise);
        writer.writeStringValue("notes", putRoutinesRequestBody_routine.notes);
        writer.writeStringValue("title", putRoutinesRequestBody_routine.title);
        writer.writeAdditionalData(putRoutinesRequestBody_routine.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePutRoutinesRequestExercise(writer: SerializationWriter, putRoutinesRequestExercise: Partial<PutRoutinesRequestExercise> | undefined | null = {}) : void {
    if (putRoutinesRequestExercise) {
        writer.writeStringValue("exercise_template_id", putRoutinesRequestExercise.exerciseTemplateId);
        writer.writeStringValue("notes", putRoutinesRequestExercise.notes);
        writer.writeNumberValue("rest_seconds", putRoutinesRequestExercise.restSeconds);
        writer.writeCollectionOfObjectValues<PutRoutinesRequestSet>("sets", putRoutinesRequestExercise.sets, serializePutRoutinesRequestSet);
        writer.writeNumberValue("superset_id", putRoutinesRequestExercise.supersetId);
        writer.writeAdditionalData(putRoutinesRequestExercise.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePutRoutinesRequestSet(writer: SerializationWriter, putRoutinesRequestSet: Partial<PutRoutinesRequestSet> | undefined | null = {}) : void {
    if (putRoutinesRequestSet) {
        writer.writeNumberValue("custom_metric", putRoutinesRequestSet.customMetric);
        writer.writeNumberValue("distance_meters", putRoutinesRequestSet.distanceMeters);
        writer.writeNumberValue("duration_seconds", putRoutinesRequestSet.durationSeconds);
        writer.writeNumberValue("reps", putRoutinesRequestSet.reps);
        writer.writeEnumValue<PutRoutinesRequestSet_type>("type", putRoutinesRequestSet.type);
        writer.writeNumberValue("weight_kg", putRoutinesRequestSet.weightKg);
        writer.writeAdditionalData(putRoutinesRequestSet.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRoutine(writer: SerializationWriter, routine: Partial<Routine> | undefined | null = {}) : void {
    if (routine) {
        writer.writeStringValue("created_at", routine.createdAt);
        writer.writeCollectionOfObjectValues<Routine_exercises>("exercises", routine.exercises, serializeRoutine_exercises);
        writer.writeNumberValue("folder_id", routine.folderId);
        writer.writeStringValue("id", routine.id);
        writer.writeStringValue("title", routine.title);
        writer.writeStringValue("updated_at", routine.updatedAt);
        writer.writeAdditionalData(routine.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRoutine_exercises(writer: SerializationWriter, routine_exercises: Partial<Routine_exercises> | undefined | null = {}) : void {
    if (routine_exercises) {
        writer.writeStringValue("exercise_template_id", routine_exercises.exerciseTemplateId);
        writer.writeNumberValue("index", routine_exercises.index);
        writer.writeStringValue("notes", routine_exercises.notes);
        writer.writeCollectionOfObjectValues<Routine_exercises_sets>("sets", routine_exercises.sets, serializeRoutine_exercises_sets);
        writer.writeNumberValue("supersets_id", routine_exercises.supersetsId);
        writer.writeStringValue("title", routine_exercises.title);
        writer.writeAdditionalData(routine_exercises.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRoutine_exercises_sets(writer: SerializationWriter, routine_exercises_sets: Partial<Routine_exercises_sets> | undefined | null = {}) : void {
    if (routine_exercises_sets) {
        writer.writeNumberValue("custom_metric", routine_exercises_sets.customMetric);
        writer.writeNumberValue("distance_meters", routine_exercises_sets.distanceMeters);
        writer.writeNumberValue("duration_seconds", routine_exercises_sets.durationSeconds);
        writer.writeNumberValue("index", routine_exercises_sets.index);
        writer.writeNumberValue("reps", routine_exercises_sets.reps);
        writer.writeNumberValue("rpe", routine_exercises_sets.rpe);
        writer.writeStringValue("type", routine_exercises_sets.type);
        writer.writeNumberValue("weight_kg", routine_exercises_sets.weightKg);
        writer.writeAdditionalData(routine_exercises_sets.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRoutineFolder(writer: SerializationWriter, routineFolder: Partial<RoutineFolder> | undefined | null = {}) : void {
    if (routineFolder) {
        writer.writeStringValue("created_at", routineFolder.createdAt);
        writer.writeNumberValue("id", routineFolder.id);
        writer.writeNumberValue("index", routineFolder.index);
        writer.writeStringValue("title", routineFolder.title);
        writer.writeStringValue("updated_at", routineFolder.updatedAt);
        writer.writeAdditionalData(routineFolder.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdatedWorkout(writer: SerializationWriter, updatedWorkout: Partial<UpdatedWorkout> | undefined | null = {}) : void {
    if (updatedWorkout) {
        writer.writeStringValue("type", updatedWorkout.type);
        writer.writeObjectValue<Workout>("workout", updatedWorkout.workout, serializeWorkout);
        writer.writeAdditionalData(updatedWorkout.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWorkout(writer: SerializationWriter, workout: Partial<Workout> | undefined | null = {}) : void {
    if (workout) {
        writer.writeStringValue("created_at", workout.createdAt);
        writer.writeStringValue("description", workout.description);
        writer.writeNumberValue("end_time", workout.endTime);
        writer.writeCollectionOfObjectValues<Workout_exercises>("exercises", workout.exercises, serializeWorkout_exercises);
        writer.writeStringValue("id", workout.id);
        writer.writeNumberValue("start_time", workout.startTime);
        writer.writeStringValue("title", workout.title);
        writer.writeStringValue("updated_at", workout.updatedAt);
        writer.writeAdditionalData(workout.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWorkout_exercises(writer: SerializationWriter, workout_exercises: Partial<Workout_exercises> | undefined | null = {}) : void {
    if (workout_exercises) {
        writer.writeStringValue("exercise_template_id", workout_exercises.exerciseTemplateId);
        writer.writeNumberValue("index", workout_exercises.index);
        writer.writeStringValue("notes", workout_exercises.notes);
        writer.writeCollectionOfObjectValues<Workout_exercises_sets>("sets", workout_exercises.sets, serializeWorkout_exercises_sets);
        writer.writeNumberValue("supersets_id", workout_exercises.supersetsId);
        writer.writeStringValue("title", workout_exercises.title);
        writer.writeAdditionalData(workout_exercises.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWorkout_exercises_sets(writer: SerializationWriter, workout_exercises_sets: Partial<Workout_exercises_sets> | undefined | null = {}) : void {
    if (workout_exercises_sets) {
        writer.writeNumberValue("custom_metric", workout_exercises_sets.customMetric);
        writer.writeNumberValue("distance_meters", workout_exercises_sets.distanceMeters);
        writer.writeNumberValue("duration_seconds", workout_exercises_sets.durationSeconds);
        writer.writeNumberValue("index", workout_exercises_sets.index);
        writer.writeNumberValue("reps", workout_exercises_sets.reps);
        writer.writeNumberValue("rpe", workout_exercises_sets.rpe);
        writer.writeStringValue("type", workout_exercises_sets.type);
        writer.writeNumberValue("weight_kg", workout_exercises_sets.weightKg);
        writer.writeAdditionalData(workout_exercises_sets.additionalData);
    }
}
export interface UpdatedWorkout extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * Indicates the type of the event (updated)
     */
    type?: string | null;
    /**
     * The workout property
     */
    workout?: Workout | null;
}
export interface Workout extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * ISO 8601 timestamp of when the workout was created.
     */
    createdAt?: string | null;
    /**
     * The workout description.
     */
    description?: string | null;
    /**
     * ISO 8601 timestamp of when the workout was recorded to have ended.
     */
    endTime?: number | null;
    /**
     * The exercises property
     */
    exercises?: Workout_exercises[] | null;
    /**
     * The workout ID.
     */
    id?: string | null;
    /**
     * ISO 8601 timestamp of when the workout was recorded to have started.
     */
    startTime?: number | null;
    /**
     * The workout title.
     */
    title?: string | null;
    /**
     * ISO 8601 timestamp of when the workout was last updated.
     */
    updatedAt?: string | null;
}
export interface Workout_exercises extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The id of the exercise template. This can be used to fetch the exercise template.
     */
    exerciseTemplateId?: string | null;
    /**
     * Index indicating the order of the exercise in the workout.
     */
    index?: number | null;
    /**
     * Notes on the exercise
     */
    notes?: string | null;
    /**
     * The sets property
     */
    sets?: Workout_exercises_sets[] | null;
    /**
     * The id of the superset that the exercise belongs to. A value of null indicates the exercise is not part of a superset.
     */
    supersetsId?: number | null;
    /**
     * Title of the exercise
     */
    title?: string | null;
}
export interface Workout_exercises_sets extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * Custom metric logged for the set (Currently only used to log floors or steps for stair machine exercises)
     */
    customMetric?: number | null;
    /**
     * Number of meters logged for the set
     */
    distanceMeters?: number | null;
    /**
     * Number of seconds logged for the set
     */
    durationSeconds?: number | null;
    /**
     * Index indicating the order of the set in the workout.
     */
    index?: number | null;
    /**
     * Number of reps logged for the set
     */
    reps?: number | null;
    /**
     * RPE (Relative perceived exertion) value logged for the set
     */
    rpe?: number | null;
    /**
     * The type of set. This can be one of 'normal', 'warmup', 'dropset', 'failure'
     */
    type?: string | null;
    /**
     * Weight lifted in kilograms.
     */
    weightKg?: number | null;
}
/**
 * The type of the set.
 */
export const PostRoutinesRequestSet_typeObject = {
    Warmup: "warmup",
    Normal: "normal",
    Failure: "failure",
    Dropset: "dropset",
} as const;
/**
 * The type of the set.
 */
export const PostWorkoutsRequestSet_typeObject = {
    Warmup: "warmup",
    Normal: "normal",
    Failure: "failure",
    Dropset: "dropset",
} as const;
/**
 * The type of the set.
 */
export const PutRoutinesRequestSet_typeObject = {
    Warmup: "warmup",
    Normal: "normal",
    Failure: "failure",
    Dropset: "dropset",
} as const;
/* tslint:enable */
/* eslint-enable */
